# yaml-language-server: $schema=https://docs.renovatebot.com/renovate-schema.json

allowedPostUpgradeCommands:
  - "^corepack use"
onboardingConfigFileName: .renovaterc.json

# HACK
packageRules:
  # support corepack integrity
  - matchDepTypes: [packageManager]
    postUpgradeTasks:
      commands:
        - "corepack use '{{{depName}}}@{{{newVersion}}}'"
